name: バグ報告
description: 期待と違う動きをする
title: 'fix: '
labels: [bug]
body:
  - type: textarea
    id: expected
    attributes:
      label: 期待した動き
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: 実際の動き
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 再現手順
      placeholder: |
        1. make up && make be
        2. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: ログ・スタックトレース
      render: shell
