name: Workflow Lint

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - name: actionlint 実行
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
